name: workingmemory
description: A ToDo List for a not so working memory
publish_to: none

version: 1.9.0

environment:
  sdk: ">=2.18.0 <3.0.0"
#  flutter: ">=1.17.0"

dependencies:

  # Facebook entry in AndroidManifest.xml
  # https://pub.dev/packages/auth
  auth: #^6.0.0
    path: ../../../packages/auth

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.0

  # https://pub.dev/packages/dbutils
  dbutils: #^2.0.0
    path: ../../../packages/dbutils

  flutter:
    sdk: flutter

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^9.0.0

  # https://pub.dev/packages/flutter_cupertino_localizations
  flutter_cupertino_localizations: ^1.0.0

  # https://pub.dev/packages/flutter_colorpicker
  flutter_colorpicker:
    git:
      url: https://github.com/AndriousSolutions/flutter_colorpicker

  # https://pub.dev/packages/firebase_crashlytics
  # Missing iOS Integration.
  firebase_crashlytics: any #^2.0.0 # ^0.2.0

  # https://pub.dev/packages/flutter_local_notifications/
  flutter_local_notifications: ^12.0.0

  # https://pub.dev/packages/flutter_ringtone_player
  flutter_ringtone_player: ^3.0.0

  # https://pub.dev/packages/flutter_system_ringtones
  flutter_system_ringtones: ^0.0.6

  # https://pub.dev/packages/fluttery_framework
  fluttery_framework: #^1.0.0
    path: ../../../packages/fluttery_framework

  # https://pub.dev/packages/remote_config
  remote_config: #^1.0.0
    path: ../../../packages/remote_config

  # https://pub.dev/packages/rxdart
#  Used by the class FlutterNotifications
  rxdart: ^0.27.3

  # https://pub.dev/packages/l10n_translator
  l10n_translator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/sql/create.sql
#     - assets/i10n/i10n.csv
     - assets/images/sunny.png
     - assets/images/moon.png
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
