name: workingmemory
description: A ToDo List for a not so working memory

dependencies:

  flutter:
    sdk: flutter

  # Database utilities from my library
  dbutils:
    path: ../../libs/db/dbutils
#    git:
#      url: git://github.com/Andrious/dbutils.git

  mvc:
    path: ../../libs/mvc
#    git:
#      url: git://github.com/AndriousSolutions/mvc.git

  prefs:
    path: ../../libs/prefs
#    git:
#      url: git://github.com/AndriousSolutions/prefs.git

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

  # https://pub.dartlang.org/packages/shared_preferences#-changelog-tab-
  shared_preferences: "^0.4.1"

  # https://pub.dartlang.org/packages/firebase_database#-changelog-tab-
  firebase_database: ^0.4.6

  # https://pub.dartlang.org/packages/firebase_core#-changelog-tab-
#  firebase_core: ^0.2.3

  # https://pub.dartlang.org/packages/firebase_auth#-changelog-tab-
  firebase_auth: "^0.5.9"

  # https://pub.dartlang.org/packages/google_sign_in#-changelog-tab-
  google_sign_in: "^3.0.3"

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
  path_provider: "^0.4.0"

  # https://pub.dartlang.org/packages/uuid#-changelog-tab-
  uuid: "^1.0.0"

  # https://pub.dartlang.org/packages/package_info#-changelog-tab-
  package_info: "^0.3.0"

  # https://pub.dartlang.org/packages/connectivity#-changelog-tab-
  connectivity: "^0.3.0"

  # https://pub.dartlang.org/packages/sqflite#-changelog-tab-
  sqflite: "^0.8.9"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
