name: workingmemory
description: A ToDo List for a not so working memory

version: 0.13.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/mvc_application
  mvc_application: ^5.0.0
#     path: ../../../packages/mvc_application
#    git:
#      url: git://github.com/AndriousSolutions/mvc_application.git

  # https://pub.dev/packages/remote_config
  remote_config: ^1.0.0
#    path: ../../../packages/remote_config

  # https://pub.dev/packages/dbutils
  dbutils: ^2.0.0
#    path: ../../../packages/dbutils

  # Facebook entry in AndroidManifest.xml
  # https://pub.dev/packages/auth
  auth: ^6.0.0
#    path: ../../Libs/auth

  # https://pub.dev/packages/sqflite
  sqflite: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: any #^0.1.0

  # https://pub.dartlang.org/packages/path_provider#-changelog-tab-
#  path_provider: ^1.0.0

  # https://pub.dartlang.org/packages/intl
  intl: any #^0.15.7

  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.0.0

  # https://pub.dev/packages/firebase_crashlytics
  # Missing iOS Integration.
  firebase_crashlytics: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
     - assets/sql/create.sql
     - assets/i10n/i10n.csv
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
