// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart' show defaultTargetPlatform;

import 'package:workingmemory/src/view.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  ///
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - you can reconfigure this by running the FlutterFire CLI again.'
              .tr,
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.'.tr,
        );
    }
  }

  ///
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK0iKD0DkUPULoJi-PuSHX7bnClSnal4k',
    appId: '1:11004453277:web:82ca5030488df92cbbcf74',
    messagingSenderId: '11004453277',
    projectId: 'todomvc-697c6',
    authDomain: 'todomvc-697c6.firebaseapp.com',
    databaseURL: 'https://todomvc-697c6.firebaseio.com',
    storageBucket: 'todomvc-697c6.appspot.com',
  );

  ///
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnKcUFhX8ofhOdFQ0UzM6GhVrznv5RJ38',
    appId: '1:11004453277:android:99ce93b08ea008aebbcf74',
    messagingSenderId: '11004453277',
    projectId: 'todomvc-697c6',
    databaseURL: 'https://todomvc-697c6.firebaseio.com',
    storageBucket: 'todomvc-697c6.appspot.com',
  );

  ///
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTFwgqTkRTtu1wEg8gi6YGBy7ZB-naqqc',
    appId: '1:11004453277:ios:0a2b3c0c479abeefbbcf74',
    messagingSenderId: '11004453277',
    projectId: 'todomvc-697c6',
    databaseURL: 'https://todomvc-697c6.firebaseio.com',
    storageBucket: 'todomvc-697c6.appspot.com',
    iosClientId:
        '11004453277-l1f9gv9mviemhbv483cqtuo4t818pai5.apps.googleusercontent.com',
    iosBundleId: 'com.andrioussolutions.workingmemory',
  );
}
