// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:workingmemory/src/view.dart';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  ///
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  ///
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9Q11SwhI5UFJDFHaaDaltMdY8YqhsyQ',
    appId: '1:761477102089:web:7e236a942206010c6e16d8',
    messagingSenderId: '761477102089',
    projectId: 'working-memory-823375',
    authDomain: 'working-memory-823375.firebaseapp.com',
    databaseURL: 'https://working-memory-823375.firebaseio.com',
    storageBucket: 'working-memory-823375.appspot.com',
  );

  ///
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpSv3EJpHCvQj4Qkur1X-Y3ooZWFo5i1E',
    appId: '1:761477102089:android:ecbfc1109769ee45',
    messagingSenderId: '761477102089',
    projectId: 'working-memory-823375',
    databaseURL: 'https://working-memory-823375.firebaseio.com',
    storageBucket: 'working-memory-823375.appspot.com',
  );

  ///
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxg26pnBaTr3_Ng4zRghXoUUyBgMCpKWA',
    appId: '1:761477102089:ios:ecbfc1109769ee45',
    messagingSenderId: '761477102089',
    projectId: 'working-memory-823375',
    databaseURL: 'https://working-memory-823375.firebaseio.com',
    storageBucket: 'working-memory-823375.appspot.com',
    androidClientId:
        '761477102089-13mh6shgvlvl0nhbucv0aurqqbsk85eh.apps.googleusercontent.com',
    iosClientId:
        '761477102089-e8hvkadoe046lk17ke57i25ld4ff1sf5.apps.googleusercontent.com',
    iosBundleId: 'com.andrioussolutions.workingmemory',
  );

  ///
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxg26pnBaTr3_Ng4zRghXoUUyBgMCpKWA',
    appId: '1:761477102089:ios:26da2a7baee2fd566e16d8',
    messagingSenderId: '761477102089',
    projectId: 'working-memory-823375',
    databaseURL: 'https://working-memory-823375.firebaseio.com',
    storageBucket: 'working-memory-823375.appspot.com',
    androidClientId:
        '761477102089-13mh6shgvlvl0nhbucv0aurqqbsk85eh.apps.googleusercontent.com',
    iosClientId:
        '761477102089-80ps6f4vbepm52qnb6b48vsvilbjr064.apps.googleusercontent.com',
    iosBundleId: 'com.andrioussolutions.workingmemory.RunnerTests',
  );
}
